feat: add 404 page on mobile app
The-Commit-Company/raven pull request #983
Opened 2024-07-28 13:54 UTC by kshitijaucharmal

- Added a 404 page
- Responsive for desktop and mobile app 
- Includes buttons for going back to login screen and channels

2024-08-01 09:36 UTC, prathameshkurunkar7 requested changes

2024-08-01 09:36 UTC, prathameshkurunkar7 commented on frontend/src/pages/404ErrorPage.tsx
> +                    <Button className="w-[30vw] h-[5vh] max-sm:w-[60vw]" variant="soft" onClick={goToLoginPage}> BACK TO LOGIN </Button>
Can we remove this button and only keep Back to Channels button, as Back to Login is not required here.

2024-08-01 09:36 UTC, prathameshkurunkar7 commented on frontend/src/pages/404ErrorPage.tsx
> +                <Text className="cal-sans text-[3vw] max-sm:text-[5vw]" align="center">  Seems Like you have wondered too far ... </Text>
Can we try to style this sub text better as this does not look clean? It can be more neat and clean imo.

2024-08-01 09:36 UTC, prathameshkurunkar7 commented on frontend/src/pages/404ErrorPage.tsx
> +    const goToLoginPage = () => {
Can remove this as well, as Back to login would be removed.

2024-08-01 09:36 UTC, prathameshkurunkar7 commented on frontend/src/pages/404ErrorPage.tsx
> +import { Link } from "react-router-dom";
We can remove unused imports in here.

2024-08-01 13:18 UTC, janhvipatil commented on frontend/src/pages/404ErrorPage.tsx
> +                    <Button className="w-[30vw] h-[5vh] max-sm:w-[60vw]" variant="soft" onClick={goToChannelPage}> BACK TO CHANNELS </Button>
The button text should not be all caps. 
This styling is unnecessary, just size='1' or size='2' should do, if you want the button width to be similar to that of the button content set width='fit-content'.
The button text can be 'Go Back'

2024-08-01 13:23 UTC, janhvipatil commented on frontend/src/pages/404ErrorPage.tsx
> +                <Text className="cal-sans text-[3vw] max-sm:text-[5vw]" align="center">  Seems Like you have wondered too far ... </Text>
we are only using 'cal-sans' for headings and buttons, this is a subtext so you can forego the 'cal-sans', also for text size use something like '6xl' or '8xl' rather than basing it on viewport width.
https://tailwindcss.com/docs/font-size

2024-08-01 13:24 UTC, janhvipatil commented on frontend/src/pages/404ErrorPage.tsx
> +                    <img src={shrugBro} ></img>
rename the icon to something like 404 page icon, or 404 image, we might not remember what that asset is being used for in the future.

2024-08-02 16:38 UTC, kshitijaucharmal commented
I'll change the 404 page as you have instructed as soon as I possibly can

2024-10-11 09:34 UTC, closed without merging